import sanitizeHTML from 'sanitize-html';

const headingAttributes = [
	'align', 'class', 'dir', 'id', 'style',
];

export function isValidEmailAddress(email: string) {
	// https://stackoverflow.com/a/201378/
	// eslint-disable-next-line no-control-regex
	return Boolean(/(?:[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/.exec(email));
}

export function sanitizeEmail(dirty: string): string {
	return sanitizeHTML(dirty, SanitizeEmailConfig);
}

export const SanitizeEmailConfig = {
	allowedTags: [
		'a',
		'b',
		'br',
		'div',
		'font',
		'h1',
		'h2',
		'h3',
		'h4',
		'h5',
		'h6',
		'hr',
		'img',
		'label',
		'li',
		'ol',
		'p',
		'span',
		'strong',
		'table',
		'td',
		'th',
		'tr',
		'u',
		'ul',
	],
	allowedAttributes: {
		a: ['class', 'href', 'id', 'style', 'target'],
		b: ['class', 'id', 'style'],
		br: ['class', 'id', 'style'],
		div: ['align', 'class', 'dir', 'id', 'style'],
		font: ['class', 'color', 'face', 'id', 'size', 'style'],
		h1: headingAttributes,
		h2: headingAttributes,
		h3: headingAttributes,
		h4: headingAttributes,
		h5: headingAttributes,
		h6: headingAttributes,
		hr: ['align', 'size', 'width'],
		img: [
			'align',
			'border',
			'class',
			'height',
			'hspace',
			'id',
			'src',
			'style',
			'usemap',
			'vspace',
			'width',
		],
		label: ['class', 'id', 'style'],
		li: ['class', 'dir', 'id', 'style', 'type'],
		ol: ['class', 'dir', 'id', 'style', 'type'],
		p: ['align', 'class', 'dir', 'id', 'style'],
		span: ['class', 'id', 'style'],
		strong: ['class', 'id', 'style'],
		table: [
			'align',
			'bgcolor',
			'border',
			'cellpadding',
			'cellspacing',
			'class',
			'dir',
			'frame',
			'id',
			'rules',
			'style',
			'width',
		],
		td: [
			'abbr',
			'align',
			'bgcolor',
			'class',
			'colspan',
			'dir',
			'height',
			'id',
			'lang',
			'rowspan',
			'scope',
			'style',
			'valign',
			'width',
		],
		th: [
			'abbr',
			'align',
			'background',
			'bgcolor',
			'class',
			'colspan',
			'dir',
			'height',
			'id',
			'lang',
			'scope',
			'style',
			'valign',
			'width',
		],
		tr: ['align', 'bgcolor', 'class', 'dir', 'id', 'style', 'valign'],
		u: ['class', 'id', 'style'],
		ul: ['class', 'dir', 'id', 'style'],
	},
	selfClosing: ['img', 'br', 'hr'],
	allowedSchemes: ['http', 'https', 'mailto', 'tel', 'sms'],
	allowedSchemesAppliedToAttributes: ['href', 'src'],
	allowProtocolRelative: false,
};
